app.name=vuln-java-lab
server.port=8080

# Intentionally bad examples for secrets scanning
db.username=admin
db.password=Password123!
api.key=FAKE_API_KEY_1234567890_TEST_ONLY
aws.access.key.id=AKIAIOSFODNN7EXAMPLE
aws.secret.access.key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

# Intentionally insecure config examples for demo purposes
security.debug=true
management.endpoints.web.exposure.include=*
